### ISSUE TITLE
TrrntZipUI build failure

### ISSUE THREAD

**Issue by dbermond** [RomVault/RVWorld#13]
I'm getting this error when trying to build `TrrntZipUI`:

```
FrmTrrntzip.cs(9,7): error CS0246: The type or namespace name 'Trrntzip' could not be found (are you missing a using directive or an assembly reference?)
FrmTrrntzip.cs(387,71): error CS0246: The type or namespace name 'TrrntZipStatus' could not be found (are you missing a using directive or an assembly reference?)
FrmTrrntzip.cs(18,26): error CS0246: The type or namespace name 'FileList' could not be found (are you missing a using directive or an assembly reference?)
```

`TrrntZipCMD` builds fine.

A git bisect shows that this is caused by commit f0a324e89c397e92667c30cae5f3c15ae5f3e5ba.

I'm building on Linux with `xbuild`.

Any chance that this can be fixed here?
